service: aquarius
frameworkVersion: '2 || 3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  environment:
    AWS_ACCESS_KEY:
    AWS_SECRET_ACCESS_KEY:
    AWS_REGION:
    DB_URL:

functions:
  putJob:
    handler: handler.put_job
    events:
      - httpApi:
          path: /
          method: post

  updateJob:
    handler: handler.update_job
    events:
      - httpApi:
          path: /{id}
          method: put

  getJobs:
    handler: handler.get_job
    events:
      - httpApi:
          path: /
          method: get

  getJob:
    handler: handler.get_job_by_id
    events:
      - httpApi:
          path: /{id}
          method: get
