service: aquarius
frameworkVersion: "2"

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-python-requirements

custom:
  serverless-offline:
    httpPort: 5000
  prune:
    automatic: true
    number: 1
  pythonRequirements:
    dockerizePip: false


provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  httpApi:
    cors: true
  environment:
    ACCESS_KEY: ${env:AWS_ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    REGION: ${env:AWS_REGION}
    DB_URL: ${env:DB_URL}
    JOB_LAMBDA_ARN: ${env:JOB_LAMBDA_ARN}

functions:
  putJob:
    handler: handlers.job.put_job
    events:
      - httpApi:
          path: /api/job
          method: post

  updateJob:
    handler: handlers.job.update_job
    events:
      - httpApi:
          path: /api/job/{id}
          method: put

  updateJobStatus:
    handler: handlers.job.update_job_status
    events:
      - httpApi:
          path: /api/job/{id}/status
          method: put

  getJobs:
    handler: handlers.job.get_job
    events:
      - httpApi:
          path: /api/job
          method: get

  getJob:
    handler: handlers.job.get_job_by_id
    events:
      - httpApi:
          path: /api/job/{id}
          method: get

  deleteJob:
    handler: handlers.job.delete_job
    events:
      - httpApi:
          path: /api/job/{id}
          method: delete

  parseRss:
    handler: handlers.url_parser.rss_parser