service: aquarius
frameworkVersion: '2 || 3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'

functions:
  job:
    handler: handler.put_job
    events:
      - httpApi:
          path: /
          method: post
