name: Deploy aquarius

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - run: npm install
    - name: serverless deploy
      uses: serverless/github-action@v3
      with:
        args: -c "serverless plugin install --name serverless-prune-plugin && serverless plugin install --name serverless-python-requirements && serverless deploy --verbose"
        entrypoint: /bin/sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.REGION }}